version: '3.8'
services:
  eureka-discovery:
    build:
      context: ./eureka-discovery-service
      dockerfile: Dockerfile
    container_name: eureka-discovery
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-discovery
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://eureka-discovery:8761/eureka/
      - eureka.client.service-url.defaultZone=http://eureka-discovery:8761/eureka/ # Ajouté ici
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true
    depends_on:
      - eureka-discovery
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
